version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn etag.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    expose:
      - 8000
    volumes:
      - /var/www/my-business-card.kz/static:/app/static
      - /var/www/my-business-card.kz/media:/app/media
      - /var/www/my-business-card.kz/logs:/app/logs
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - database_network
      - https
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - /var/www/my-business-card.kz/static:/app/static
      - /var/www/my-business-card.kz/media:/app/media
    networks:
      - https
    depends_on:
      - web
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - database_network
    restart: always

volumes:
  postgres_data:

networks:
  database_network:
    external: true
  https:
    external: true 